version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # container_name: mongodb  
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: max 
      # MONGO_INITDB_ROOT_PASSWORD: secret
      #- MONGO_INITDB_ROOT_USERNAME=max
    env_file:
      - ./env/mongo.env  
    # networks:
    #   - goals-net    
  backend:
    # build: ./backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   some-arg: 1
    ports: 
      - '80:80'  
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    # container_name: goals-backend
    env_file:
      - ./env/backend.env  
    depends_on: 
      - mongodb
  frontend:  
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  
    volumes:
      - ./frontend/src:/app/src
    # container_name: goals-frontend  
    stdin_open: true # -open input connection
    tty: true # terminal 
    depends_on: 
      - backend

volumes:
  data:
  logs: